version: '3.4'

services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      SERVER_REWRITEBASEPATH: true
      SERVER_BASEPATH: /kibana
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'

  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      TZ: 'UTC'
      PGTZ: 'UTC'
      POSTGRES_DB: onlinesales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  elastic-data:  