version: '3.4'

services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - 9200:9200
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      SERVER_REWRITEBASEPATH: true
      SERVER_BASEPATH: /kibana
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'

  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      TZ: 'UTC'
      PGTZ: 'UTC'
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  onlinesales:
    container_name: onlinesales
    image: wavepoint/onlinesales:latest
    environment:
      POSTGRES__SERVER: postgres
      POSTGRES__DATABASE: ${PG_DB}
      POSTGRES__USERNAME: ${PG_USER}
      POSTGRES__PASSWORD: ${PG_PWD} 
      ELASTIC__SERVER: elastic
    ports: 
      - 80:80

volumes:  
  postgres-data:
  elastic-data: